  GNU nano 2.2.6 File: .travis.yml language: ruby
 rvm: - 2.2.0
 - 2.2.2
 script: bundle exec rspec spec before_install: gem install bundler -v 1.10.6
                                                                        
